dist: trusty
language: erlang
sudo: false
otp_release:
  - 20.0
  - 19.3
services:
  - docker
install:
  - make all
script:
  - make ct
  - ./travis.sh test antidote
  - ./travis.sh test riak
  - ./travis.sh bench antidote
  - ./travis.sh bench riak
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
