dist: trusty
language: erlang
sudo: false
otp_release:
  - 20.0
  - 19.3
services:
  - docker
install:
  - make all
before_script:
  - ./rebar3 as test,antidote,riak,redis release
script:
  - make eunit
  - make ct
  - make bench
  - make test-multiple-releases
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
