dist: trusty
language: erlang
sudo: false
otp_release:
  - 20.0
services:
  - docker
install:
  - make all
script:
  - make eunit
  - make ct
  - make bench
  - make test-multiple-releases
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
